apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  type: ExternalName
  externalName: cibg-lion.westeurope.cloudapp.azure.com
status:
  loadBalancer: {}
